### ISSUE TITLE
Refresh in combination with o

### ISSUE THREAD

**Issue by xyproto** [antonmedv/llama#4]
`llama` might need a refresh after launching applications like the `o` text editor.

Steps to reproduce:

* Use `alacritty`.
* Install **o**: `go install github.com/xyproto/o@latest`
* Set **EDITOR**:`export EDITOR=o`
* Launch **llama** and open a text file.
* Quit `o` with `ctrl-q`.
* Move arrows up and down.
* Observe that some of the text in **llama** is gone.

Thanks for creating **llama**, it was quick to install and fun to use. :+1:

**Comment by antonmedv** [comment]
Will try to solve it) Thanks 😊

**Comment by antonmedv** [comment]
Try it now.  Should be fixed

**Comment by xyproto** [comment]
Cool, will test 🙂

**Comment by xyproto** [comment]
This is still an issue here, both in `konsole` and in `alacritty`:

After running cloning and building the latest commit from `master`, running `EDITOR=o ./llama` and then opening `README.md` by using the arrow keys and return, the files opens up nicely. However, when quitting the editor by pressing `ctrl-q`, the text in `llama` is not redrawn until the arrow keys are pressed and the text selection box is moved up and down over text.

**Comment by antonmedv** [comment]
Can you try this release as well https://github.com/antonmedv/llama/releases/tag/v1.1.0?

**Comment by xyproto** [comment]
My bad, I tested with the wrong commit!

It works great with `v1.1.0` and also `master`! Thanks. :)
